/**
 * @class centraliza y almacena nombres de los action de redux
 */
const CONSTANTS = {
 REGISTRO: 'REGISTRO',
 LOGIN: 'LOGIN',
 ESTABLECERSESION: 'ESTABLECERSESION',
 CERRARSESION: 'CERRARSESION',
 LOADING: 'LOADING',
 CLOUDINARY_NAME: 'https://api.cloudinary.com/v1_1/dqr7rxrzc/auto/upload',
 CLOUDINARY_PRESET: 'yqsbucjn',
 CARGAR_IMAGEN_PUBLICACION: 'CARGAR_IMAGEN_PUBLICACION',
 SUBIR_PUBLICACION:'SUBIR_PUBLICACION',
 ANADIR_MARKERS:'ANADIR_MARKERS',
 CAMBIAR_EMAIL: 'CAMBIAR_EMAIL',
 Obtener_Perfil: 'Obtener_Perfil',
 ENVIAR_CONTACTO:"ENVIAR_CONTACTO",
}
export default CONSTANTS;